# Generated by Django 2.1.4 on 2019-01-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('quantity_from', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='操作前数量')),
                ('quantity_to', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='操作后数量')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item', verbose_name='物品')),
                ('location_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from_here', to='inventory.Location', verbose_name='从')),
                ('location_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to_here', to='inventory.Location', verbose_name='到')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '物品操作记录',
                'verbose_name_plural': '物品操作记录',
                'ordering': ['-time'],
            },
        ),
    ]
