# Generated by Django 2.1.5 on 2019-01-20 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 6, 1, 50, 728404, tzinfo=utc), verbose_name='操作时间'),
        ),
    ]
