# Generated by Django 2.1.4 on 2019-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlog',
            name='quantity_from',
            field=models.FloatField(blank=True, default=0, verbose_name='操作前数量'),
        ),
        migrations.AlterField(
            model_name='itemlog',
            name='quantity_to',
            field=models.FloatField(blank=True, default=0, verbose_name='操作后数量'),
        ),
    ]
