# Generated by Django 2.1.5 on 2019-01-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlog',
            options={'ordering': ['-time'], 'verbose_name': '物品操作记录', 'verbose_name_plural': '物品操作记录'},
        ),
    ]
