# Generated by Django 2.1.1 on 2019-01-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0002_auto_20190120_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlog',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from_here', to='inventory.Location', verbose_name='从'),
        ),
        migrations.AlterField(
            model_name='itemlog',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to_here', to='inventory.Location', verbose_name='到'),
        ),
    ]
