# Generated by Django 2.1.5 on 2019-01-20 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0002_auto_20190120_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间'),
        ),
    ]
