# Generated by Django 2.1.5 on 2019-02-03 11:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0002_auto_20190131_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlog',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='quantity_from',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='quantity_to',
        ),
        migrations.AddField(
            model_name='itemlog',
            name='extra_data_to',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=0, verbose_name='操作前数量'),
        ),
    ]
