# Generated by Django 2.1.5 on 2019-01-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('trace_item', '0003_auto_20190120_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item', verbose_name='物品'),
        ),
    ]
