# Generated by Django 2.1.5 on 2019-02-03 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trace_item', '0003_auto_20190203_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlog',
            name='extra_data_to',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=0, verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='itemlog',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to_here', to='inventory.Location', verbose_name='位置'),
        ),
    ]
