language: python
python:
  - "3.6"
install:
  - pip install -r
before_script:
  - python manage.py makemigrations inventory login
  - python manage.py migrate
script: python manage.py runserver 0.0.0.0:8000
