language: python
python:
  - '3.6'
before_install:
  - openssl aes-256-cbc -K $encrypted_3c5635537c13_key -iv $encrypted_3c5635537c13_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script: ssh -o StrictHostKeyChecking=no ubuntu@118.25.94.244 "./lit-auto-deploy.sh"
addons:
  ssh_known_hosts: 118.25.94.244
