# Generated by Django 2.1.5 on 2019-01-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('real_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '邮箱白名单',
                'verbose_name_plural': '邮箱白名单',
            },
        ),
    ]
