# Generated by Django 2.1.1 on 2019-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_staff_+', to='login.User', verbose_name='下属用户'),
        ),
    ]
