# Generated by Django 2.1.5 on 2019-01-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_allowedemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemails',
            name='real_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
