# Generated by Django 2.1.1 on 2019-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190118_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否管理员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='_user_staff_+', to='login.User', verbose_name='关联用户'),
        ),
    ]
