# Generated by Django 2.1.5 on 2019-02-03 14:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190131_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='设置'),
        ),
    ]
