# Generated by Django 2.1.5 on 2019-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staffUser', to='login.User', verbose_name='关联用户'),
        ),
    ]
