# Generated by Django 2.1.1 on 2019-02-13 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_last_online_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_online_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
