# Generated by Django 2.1.1 on 2019-01-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190119_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staffUser', to='login.User', verbose_name='被管理员工'),
        ),
    ]
