# Generated by Django 2.1.1 on 2019-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-time'], 'verbose_name': '日志', 'verbose_name_plural': '日志'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='result',
        ),
        migrations.AddField(
            model_name='log',
            name='_from',
            field=models.TextField(blank=True, null=True, verbose_name='操作前'),
        ),
        migrations.AddField(
            model_name='log',
            name='_to',
            field=models.TextField(blank=True, null=True, verbose_name='操作后'),
        ),
    ]
