# Generated by Django 2.1.1 on 2019-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190209_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='obj',
        ),
        migrations.AddField(
            model_name='log',
            name='_id',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='类型'),
        ),
    ]
