# Generated by Django 2.1.1 on 2019-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20190209_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='attribute',
            field=models.TextField(blank=True, null=True, verbose_name='属性'),
        ),
    ]
