# Generated by Django 2.1.1 on 2019-02-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_log_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='_to',
            new_name='after',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='_from',
            new_name='before',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='_id',
            new_name='obj_id',
        ),
    ]
