# Generated by Django 2.1.4 on 2019-01-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='', max_length=32, verbose_name='单位')),
                ('attribute', models.TextField(blank=True, verbose_name='属性')),
                ('user', models.ManyToManyField(default='', to='login.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['id'],
            },
        ),
    ]
