# Generated by Django 2.1.5 on 2019-01-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='', max_length=32, verbose_name='单位')),
                ('attribute', models.TextField(blank=True, verbose_name='属性')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('allowed_users', models.ManyToManyField(blank=True, to='login.User', verbose_name='允许用户')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['update_time'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=32, verbose_name='路径')),
                ('allowed_users', models.ManyToManyField(blank=True, default='', to='login.User', verbose_name='允许用户')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentPath', to='inventory.Location', verbose_name='父位置')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
            },
        ),
        migrations.CreateModel(
            name='LocationPermissionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(default='', max_length=256, verbose_name='申请理由')),
                ('approved', models.BooleanField(default=False, verbose_name='是否同意')),
                ('rejected', models.BooleanField(default=False, verbose_name='是否拒绝')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='申请时间')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User', verbose_name='申请人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location', verbose_name='申请位置')),
            ],
            options={
                'verbose_name': '位置申请',
                'verbose_name_plural': '位置申请',
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='inventory.Location', verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.User', verbose_name='所有者'),
        ),
    ]
