# Generated by Django 2.1.5 on 2019-01-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-update_time'], 'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AlterModelOptions(
            name='locationpermissionapplication',
            options={'ordering': ['-time'], 'verbose_name': '位置申请', 'verbose_name_plural': '位置申请'},
        ),
    ]
