# Generated by Django 2.1.1 on 2019-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='模块名称'),
        ),
    ]
