# Generated by Django 2.1.1 on 2019-01-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='path',
            field=models.CharField(max_length=32, verbose_name='路径'),
        ),
    ]
