# Generated by Django 2.1.5 on 2019-01-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190130_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpermissionapplication',
            options={'ordering': ['closed', 'id'], 'verbose_name': '位置申请', 'verbose_name_plural': '位置申请'},
        ),
    ]
