# Generated by Django 2.1.5 on 2019-01-15 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190114_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location', verbose_name='位置'),
        ),
    ]
