# Generated by Django 2.1.4 on 2019-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190121_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpermissionapplication',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='申请理由'),
        ),
    ]
