# Generated by Django 2.1.1 on 2019-01-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
