# Generated by Django 2.1.4 on 2019-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190130_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(blank=True, default=0, verbose_name='数量'),
        ),
    ]
