# Generated by Django 2.1.4 on 2019-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='单位'),
        ),
    ]
