# Generated by Django 2.1.1 on 2019-01-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190110_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc1', models.CharField(max_length=45, verbose_name='位置1')),
                ('loc2', models.CharField(max_length=45, verbose_name='位置2')),
                ('loc3', models.CharField(max_length=45, verbose_name='位置3')),
                ('loc4', models.CharField(max_length=45, verbose_name='位置4')),
                ('loc5', models.CharField(max_length=45, verbose_name='位置5')),
            ],
            options={
                'ordering': ['loc1'],
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id'], 'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AlterField(
            model_name='material',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Location', verbose_name='位置'),
        ),
    ]
