# Generated by Django 2.1.4 on 2019-01-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190122_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpermissionapplication',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor', to='login.User', verbose_name='处理人'),
        ),
    ]
