# Generated by Django 2.1.1 on 2019-01-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190111_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc1',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='位置1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc2',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='位置2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc3',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='位置3'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc4',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='位置4'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc5',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='位置5'),
        ),
    ]
