# Generated by Django 2.1.1 on 2019-01-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190120_1117'),
        ('inventory', '0008_auto_20190115_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, default='', to='login.User', verbose_name='允许用户'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to='login.User', verbose_name='所有者'),
        ),
    ]
