# Generated by Django 2.1.1 on 2019-01-12 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_auto_20190113_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='user',
        ),
        migrations.AddField(
            model_name='material',
            name='user',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
