# Generated by Django 2.1.1 on 2019-01-29 11:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190127_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='扩展数据'),
        ),
    ]
