# Generated by Django 2.1.1 on 2019-02-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_settings'),
        ('inventory', '0010_remove_item_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to='login.User', verbose_name='白名单'),
        ),
    ]
