# Generated by Django 2.1.1 on 2019-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190113_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='user',
            field=models.ManyToManyField(default='', to='login.User', verbose_name='用户'),
        ),
    ]
