# Generated by Django 2.1.1 on 2019-01-29 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='扩展数据'),
        ),
    ]
