# Generated by Django 2.1.1 on 2019-01-29 11:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20190129_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, verbose_name='扩展数据'),
        ),
    ]
