# Generated by Django 2.1.5 on 2019-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itemtemplate_allowed_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtemplate',
            options={'ordering': ['-create_time'], 'verbose_name': '物品模板', 'verbose_name_plural': '物品模板'},
        ),
    ]
