# Generated by Django 2.1.5 on 2019-02-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20190204_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='key_name_placeholder',
            field=models.CharField(default='用于显示的名称', max_length=128, verbose_name='关键字段占位符'),
        ),
    ]
