# Generated by Django 2.1.4 on 2019-02-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_itemtemplate_key_name_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtemplate',
            options={'ordering': ['-create_time'], 'verbose_name': '模板', 'verbose_name_plural': '模板'},
        ),
    ]
