# Generated by Django 2.1.1 on 2019-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190213_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='custom ID'),
        ),
    ]
