# Generated by Django 2.1.4 on 2019-01-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_itemtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_instance', to='inventory.ItemTemplate', verbose_name='扩展数据模板'),
        ),
    ]
