# Generated by Django 2.1.4 on 2019-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_item_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='name',
            field=models.CharField(max_length=64, verbose_name='模块ID'),
        ),
    ]
