# Generated by Django 2.1.1 on 2019-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_item_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='custom_id_format',
            field=models.CharField(default='%date%-%id%', max_length=128, verbose_name='custom_id_format'),
        ),
    ]
