# Generated by Django 2.1.5 on 2019-02-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_itemtemplate_custom_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='custom_id_name',
            field=models.CharField(default='ID', max_length=128, verbose_name='custom_id_name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='custom_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='自定编号'),
        ),
    ]
