# Generated by Django 2.1.5 on 2019-02-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20190217_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=128, verbose_name='模式')),
                ('next_id', models.IntegerField(default=1)),
            ],
        ),
    ]
