# Generated by Django 2.1.4 on 2019-01-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=32)),
                ('traffic_cnt', models.IntegerField()),
                ('locreq_cnt', models.IntegerField()),
                ('itemlog_cnt', models.IntegerField()),
                ('need_update', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='URL')),
                ('response_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Response Time')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Request Time')),
                ('ip', models.CharField(max_length=16, verbose_name='IP')),
                ('user_agent', models.CharField(default='unknown', max_length=256, null=True, verbose_name='User-Agent')),
                ('http_status', models.CharField(max_length=16, verbose_name='HTTP Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_traffic', to='login.User', verbose_name='User')),
            ],
        ),
    ]
