# Generated by Django 2.1.5 on 2019-01-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64, verbose_name='URL')),
                ('response_time', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Response Time')),
                ('datatime', models.DateTimeField(auto_now_add=True, verbose_name='Request Time')),
                ('ip', models.CharField(max_length=16, verbose_name='IP')),
                ('http_status', models.CharField(max_length=16, verbose_name='HTTP Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='login.User', verbose_name='User')),
            ],
        ),
    ]
