# Generated by Django 2.1.1 on 2019-01-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='user_agent',
            field=models.TextField(default='unknown', verbose_name='User-Agent'),
        ),
    ]
