# Generated by Django 2.1.4 on 2019-01-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20190130_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='response_time',
            field=models.FloatField(default=0, verbose_name='Response Time'),
        ),
    ]
