# Generated by Django 2.1.5 on 2019-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_auto_20190123_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='url',
            field=models.CharField(max_length=128, verbose_name='URL'),
        ),
    ]
