# Generated by Django 2.1.1 on 2019-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_auto_20190123_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='user_agent',
            field=models.CharField(default='unknown', max_length=256, null=True, verbose_name='User-Agent'),
        ),
    ]
