# Generated by Django 2.1.5 on 2019-01-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_traffic_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=32)),
                ('traffic_cnt', models.IntegerField()),
                ('locreq_cnt', models.IntegerField()),
                ('itemlog_cnt', models.IntegerField()),
            ],
        ),
    ]
