# Generated by Django 2.1.5 on 2019-01-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_calendercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendercache',
            name='need_update',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
