# Generated by Django 2.1.5 on 2019-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_calendercache_need_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendercache',
            name='need_update',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
