# Generated by Django 2.1.1 on 2019-01-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20190126_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_traffic', to='login.User', verbose_name='User'),
        ),
    ]
